### ISSUE TITLE
CLI and NPM

### ISSUE THREAD

**Issue by OleVik** [gyoshev/cuttle#1]
It would be very helpful if the API was accessible from CLI and available from the NPM-directory, so you could install it globally (`npm install -g cuttle`) and then write `cuttle.suggest("#ae465f", "#aeae46", "sass")` and get `[ { difference: 0.4477, format: "adjust-hue($input, 75)" } ]` returned.

**Comment by gyoshev** [comment]
@OleVik Whoa, seems I missed the notification for this issue. Thanks for the great suggestion -- it is likely to happen soon.

**Comment by gyoshev** [comment]
Cuttle is now [available on NPM](https://www.npmjs.com/package/cuttle), and can be run as a command-line tool. See the docs on the NPM page, or in the README.
